"""
Performance validation testing framework.
Validates that identified performance bugs actually improve performance when fixed.
"""

import subprocess
import tempfile
import time
import statistics
from pathlib import Path
from typing import Dict, List, Tuple, Optional
from dataclasses import dataclass
import logging
import json

logger = logging.getLogger(__name__)

@dataclass
class PerformanceTestResult:
    """Results of performance testing"""
    bug_id: str
    category: str
    buggy_time_ms: float
    fixed_time_ms: float
    improvement_factor: float
    improvement_percentage: float
    test_runs: int
    statistical_significance: bool

class PerformanceValidator:
    """
    Validates performance improvements by running actual tests.
    Creates microbenchmarks for buggy vs fixed code versions.
    """
    
    def __init__(self, java_home: Optional[str] = None):
        self.java_home = java_home
        self.test_runs = 10  # Number of runs for statistical validity
        
    def validate_bug_fix(self, bug: Dict) -> Optional[PerformanceTestResult]:
        """
        Validate that a bug fix actually improves performance.
        Returns performance test results.
        """
        if not bug.get('modified_methods'):
            return None
        
        method = bug['modified_methods'][0]
        if not isinstance(method, dict):
            return None
        
        buggy_code = method.get('buggy_code', '')
        fixed_code = method.get('fixed_code', '')
        
        if not buggy_code or not fixed_code:
            return None
        
        # Create test harness
        test_class = self._create_test_harness(
            bug['identifier'],
            buggy_code,
            fixed_code,
            bug['category']
        )
        
        if not test_class:
            return None
        
        # Run performance tests
        buggy_times = self._run_performance_test(test_class, 'buggy')
        fixed_times = self._run_performance_test(test_class, 'fixed')
        
        if not buggy_times or not fixed_times:
            return None
        
        # Calculate statistics
        buggy_avg = statistics.mean(buggy_times)
        fixed_avg = statistics.mean(fixed_times)
        
        improvement_factor = buggy_avg / fixed_avg if fixed_avg > 0 else 1.0\n",
        improvement_pct = (buggy_avg - fixed_avg) / buggy_avg * 100 if buggy_avg > 0 else 0.0\n",
        \n",
        # Statistical significance test (simplified)\n",
        "significance = self._test_significance(buggy_times, fixed_times)\n        \n",
    "        return PerformanceTestResult(\n",
    "            bug_id=bug['identifier'],\n",
    "            category=bug['category'],\n",
    "            buggy_time_ms=buggy_avg,\n",
    "            fixed_time_ms=fixed_avg,\n",
    "            improvement_factor=improvement_factor,\n",
    "            improvement_percentage=improvement_pct,\n",
    "            test_runs=len(buggy_times),\n",
    "            statistical_significance=significance\n",
    "        )\n",
    "    \n",
    "    def _create_test_harness(self, bug_id: str, buggy_code: str, \n",
    "                            fixed_code: str, category: str) -> Optional[str]:\n",
    "        \"\"\"Create Java test harness for performance comparison\"\"\"\n",
    "        \n",
    "        # Generate test data based on category\n",
    "        test_data = self._generate_test_data(category)\n",
    "        \n",
    "        # Create test class template\n",
    "        test_template = f\"\"\"\n",
    "import java.util.*;\n",
    "import java.io.*;\n",
    "\n",
    "public class PerformanceTest_{bug_id.replace('-', '_')} {{\n",
    "    \n",
    "    // Test data\n",
    "    {test_data}\n",
    "    \n",
    "    // Buggy implementation\n",
    "    public void buggyMethod() {{\n",
    "        {self._wrap_method_code(buggy_code)}\n",
    "    }}\n",
    "    \n",
    "    // Fixed implementation\n",
    "    public void fixedMethod() {{\n",
    "        {self._wrap_method_code(fixed_code)}\n",
    "    }}\n",
    "    \n",
    "    // Performance test runner\n",
    "    public static void main(String[] args) {{\n",
    "        PerformanceTest_{bug_id.replace('-', '_')} test = new PerformanceTest_{bug_id.replace('-', '_')}();\n",
    "        String method = args.length > 0 ? args[0] : \"buggy\";\n",
    "        \n",
    "        long startTime = System.nanoTime();\n",
    "        \n",
    "        if (\"buggy\".equals(method)) {{\n",
    "            test.buggyMethod();\n",
    "        }} else {{\n",
    "            test.fixedMethod();\n",
    "        }}\n",
    "        \n",
    "        long endTime = System.nanoTime();\n",
    "        long duration = (endTime - startTime) / 1_000_000; // Convert to ms\n",
    "        \n",
    "        System.out.println(duration);\n",
    "    }}\n",
    "}}\n",
    "\"\"\"\n",
    "        \n",
    "        return test_template\n",
    "    \n",
    "    def _generate_test_data(self, category: str) -> str:\n",
    "        \"\"\"Generate appropriate test data for each category\"\"\"\n",
    "        \n",
    "        if category == 'algorithmic_inefficiency':\n",
    "            return \"\"\"\n",
    "    private List<Integer> items = new ArrayList<>();\n",
    "    {\n",
    "        for (int i = 0; i < 1000; i++) {\n",
    "            items.add(i);\n",
    "        }\n",
    "    }\n",
    "            \"\"\"\n",
    "        \n",
    "        elif category == 'memory_usage':\n",
    "            return \"\"\"\n",
    "    private List<String> strings = new ArrayList<>();\n",
    "    {\n",
    "        for (int i = 0; i < 500; i++) {\n",
    "            strings.add(\"String\" + i);\n",
    "        }\n",
    "    }\n",
    "            \"\"\"\n",
    "        \n",
    "        elif category == 'redundant_computation':\n",
    "            return \"\"\"\n",
    "    private double[] values = new double[100];\n",
    "    {\n",
    "        for (int i = 0; i < values.length; i++) {\n",
    "            values[i] = Math.random() * 100;\n",
    "        }\n",
    "    }\n",
    "            \"\"\"\n",
    "        \n",
    "        elif category == 'io_inefficiency':\n",
    "            return \"\"\"\n",
    "    private byte[] data = new byte[10000];\n",
    "    {\n",
    "        for (int i = 0; i < data.length; i++) {\n",
    "            data[i] = (byte)(i % 256);\n",
    "        }\n",
    "    }\n",
    "            \"\"\"\n",
    "        \n",
    "        else:  # cpu_overhead\n",
    "            return \"\"\"\n",
    "    private List<Integer> numbers = new ArrayList<>();\n",
    "    {\n",
    "        for (int i = 0; i < 1000; i++) {\n",
    "            numbers.add(i);\n",
    "        }\n",
    "    }\n",
    "            \"\"\"\n",
    "    \n",
    "    def _wrap_method_code(self, code: str) -> str:\n",
    "        \"\"\"Wrap method code to make it runnable\"\"\"\n",
    "        # Simplified wrapper - in production, would need more sophisticated code adaptation\n",
    "        if 'return' not in code:\n",
    "            # Add loops for demonstration\n",
    "            return f\"\"\"\n",
    "        for (int iteration = 0; iteration < 100; iteration++) {{\n",
    "            {code}\n",
    "        }}\n",
    "            \"\"\"\n",
    "        return code\n",
    "    \n",
    "    def _run_performance_test(self, test_class: str, method: str) -> List[float]:\n",
    "        \"\"\"Run performance test and return execution times\"\"\"\n",
    "        times = []\n",
    "        \n",
    "        with tempfile.TemporaryDirectory() as tmpdir:\n",
    "            # Write test class to file\n",
    "            class_name = test_class.split('class ')[1].split(' ')[0]\n",
    "            java_file = Path(tmpdir) / f\"{class_name}.java\"\n",
    "            \n",
    "            with open(java_file, 'w') as f:\n",
    "                f.write(test_class)\n",
    "            \n",
    "            try:\n",
    "                # Compile\n",
    "                subprocess.run(\n",
    "                    ['javac', str(java_file)],\n",
    "                    cwd=tmpdir, check=True, capture_output=True\n",
    "                )\n",
    "                \n",
    "                # Run multiple times\n",
    "                for _ in range(self.test_runs):\n",
    "                    result = subprocess.run(\n",
    "                        ['java', class_name, method],\n",
    "                        cwd=tmpdir, capture_output=True, text=True, timeout=30\n",
    "                    )\n",
    "                    \n",
    "                    if result.returncode == 0:\n",
    "                        try:\n",
    "                            time_ms = float(result.stdout.strip())\n",
    "                            times.append(time_ms)\n",
    "                        except ValueError:\n",
    "                            pass\n",
    "                \n",
    "            except Exception as e:\n",
    "                logger.debug(f\"Performance test failed: {e}\")\n",
    "        \n",
    "        return times\n",
    "    \n",
    "    def _test_significance(self, buggy_times: List[float], \n",
    "                          fixed_times: List[float]) -> bool:\n",
    "        \"\"\"Simple statistical significance test\"\"\"\n",
    "        if len(buggy_times) < 3 or len(fixed_times) < 3:\n",
    "            return False\n",
    "        \n",
    "        # Simple test: improvement > 2 standard deviations\n",
    "        buggy_mean = statistics.mean(buggy_times)\n",
    "        fixed_mean = statistics.mean(fixed_times)\n",
    "        \n",
    "        if buggy_mean <= fixed_mean:\n",
    "            return False\n",
    "        \n",
    "        buggy_std = statistics.stdev(buggy_times) if len(buggy_times) > 1 else 0\n",
    "        improvement = buggy_mean - fixed_mean\n",
    "        \n",
    "        return improvement > 2 * buggy_std\n",
    "    \n",
    "    def validate_dataset(self, bugs: List[Dict]) -> List[PerformanceTestResult]:\n",
    "        \"\"\"Validate performance improvements for a dataset of bugs\"\"\"\n",
    "        results = []\n",
    "        \n",
    "        for i, bug in enumerate(bugs[:5]):  # Test subset for demonstration\n",
    "            logger.info(f\"Validating bug {i+1}/{min(5, len(bugs))}: {bug.get('identifier')}\")\n",
    "            \n",
    "            result = self.validate_bug_fix(bug)\n",
    "            if result:\n",
    "                results.append(result)\n",
    "        \n",
    "        return results\n",
    "    \n",
    "    def generate_validation_report(self, results: List[PerformanceTestResult]) -> Dict:\n",
    "        \"\"\"Generate performance validation report\"\"\"\n",
    "        if not results:\n",
    "            return {\"message\": \"No valid performance tests\"}\n",
    "        \n",
    "        # Calculate statistics\n",
    "        improvements = [r.improvement_percentage for r in results]\n",
    "        factors = [r.improvement_factor for r in results]\n",
    "        significant = [r for r in results if r.statistical_significance]\n",
    "        \n",
    "        by_category = {}\n",
    "        for result in results:\n",
    "            cat = result.category\n",
    "            if cat not in by_category:\n",
    "                by_category[cat] = []\n",
    "            by_category[cat].append(result.improvement_percentage)\n",
    "        \n",
    "        report = {\n",
    "            \"total_tests\": len(results),\n",
    "            \"statistically_significant\": len(significant),\n",
    "            \"significance_rate\": len(significant) / len(results) * 100,\n",
    "            \"average_improvement_pct\": statistics.mean(improvements),\n",
    "            \"median_improvement_pct\": statistics.median(improvements),\n",
    "            \"average_improvement_factor\": statistics.mean(factors),\n",
    "            \"by_category\": {\n",
    "                cat: {\n",
    "                    \"count\": len(imps),\n",
    "                    \"avg_improvement\": statistics.mean(imps),\n",
    "                    \"median_improvement\": statistics.median(imps)\n",
    "                }\n",
    "                for cat, imps in by_category.items()\n",
    "            },\n",
    "            \"results\": [{\n",
    "                \"bug_id\": r.bug_id,\n",
    "                \"category\": r.category,\n",
    "                \"improvement_pct\": r.improvement_percentage,\n",
    "                \"improvement_factor\": r.improvement_factor,\n",
    "                \"significant\": r.statistical_significance\n",
    "            } for r in results]\n",
    "        }\n",
    "        \n",
    "        return report

class SyntheticBenchmarkGenerator:\n",
    "    \"\"\"\n",
    "    Generates synthetic benchmarks based on performance bug categories.\n",
    "    Used when actual bug code cannot be compiled/run.\n",
    "    \"\"\"\n",
    "    \n",
    "    def __init__(self):\n",
    "        self.benchmark_templates = self._load_templates()\n",
    "    \n",
    "    def _load_templates(self) -> Dict[str, Dict]:\n",
    "        \"\"\"Load benchmark templates for each category\"\"\"\n",
    "        return {\n",
    "            'algorithmic_inefficiency': {\n",
    "                'buggy': \"\"\"\n",
    "public static void nestedLoopSearch(List<Integer> items, int target) {\n",
    "    for (int i = 0; i < items.size(); i++) {\n",
    "        for (int j = 0; j < items.size(); j++) {\n",
    "            if (items.get(i) == target) {\n",
    "                return;\n",
    "            }\n",
    "        }\n",
    "    }\n",
    "}\n",
    "                \"\"\",\n",
    "                'fixed': \"\"\"\n",
    "public static void optimizedSearch(List<Integer> items, int target) {\n",
    "    for (int item : items) {\n",
    "        if (item == target) {\n",
    "            return;\n",
    "        }\n",
    "    }\n",
    "}\n",
    "                \"\"\"\n",
    "            },\n",
    "            'memory_usage': {\n",
    "                'buggy': \"\"\"\n",
    "public static String concatenateStrings(List<String> items) {\n",
    "    String result = \"\";\n",
    "    for (String item : items) {\n",
    "        result += item + \", \";\n",
    "    }\n",
    "    return result;\n",
    "}\n",
    "                \"\"\",\n",
    "                'fixed': \"\"\"\n",
    "public static String concatenateStrings(List<String> items) {\n",
    "    StringBuilder sb = new StringBuilder(items.size() * 20);\n",
    "    for (String item : items) {\n",
    "        sb.append(item).append(\", \");\n",
    "    }\n",
    "    return sb.toString();\n",
    "}\n",
    "                \"\"\"\n",
    "            },\n",
    "            'redundant_computation': {\n",
    "                'buggy': \"\"\"\n",
    "public static double calculateDistances(List<Point> points, Point center) {\n",
    "    double total = 0;\n",
    "    for (Point p : points) {\n",
    "        total += Math.sqrt(Math.pow(p.x - center.x, 2) + Math.pow(p.y - center.y, 2));\n",
    "        double sameCalc = Math.sqrt(Math.pow(p.x - center.x, 2) + Math.pow(p.y - center.y, 2));\n",
    "        System.out.println(sameCalc);\n",
    "    }\n",
    "    return total;\n",
    "}\n",
    "                \"\"\",\n",
    "                'fixed': \"\"\"\n",
    "public static double calculateDistances(List<Point> points, Point center) {\n",
    "    double total = 0;\n",
    "    for (Point p : points) {\n",
    "        double distance = Math.sqrt(Math.pow(p.x - center.x, 2) + Math.pow(p.y - center.y, 2));\n",
    "        total += distance;\n",
    "        System.out.println(distance);\n",
    "    }\n",
    "    return total;\n",
    "}\n",
    "                \"\"\"\n",
    "            }\n",
    "        }\n",
    "    \n",
    "    def generate_benchmark(self, category: str, size: int = 1000) -> Dict[str, str]:\n",
    "        \"\"\"Generate a complete benchmark for a category\"\"\"\n",
    "        template = self.benchmark_templates.get(category)\n",
    "        if not template:\n",
    "            return {}\n",
    "        \n",
    "        # Add data generation and test harness\n",
    "        benchmark = {\n",
    "            'buggy': self._create_complete_benchmark(template['buggy'], category, size),\n",
    "            'fixed': self._create_complete_benchmark(template['fixed'], category, size)\n",
    "        }\n",
    "        \n",
    "        return benchmark\n",
    "    \n",
    "    def _create_complete_benchmark(self, method_code: str, category: str, size: int) -> str:\n",
    "        \"\"\"Create complete runnable benchmark\"\"\"\n",
    "        return f\"\"\"\n",
    "import java.util.*;\n",
    "import java.io.*;\n",
    "\n",
    "class Point {{\n",
    "    double x, y;\n",
    "    Point(double x, double y) {{ this.x = x; this.y = y; }}\n",
    "}}\n",
    "\n",
    "public class Benchmark_{category.title().replace('_', '')} {{\n",
    "    \n",
    "    {method_code}\n",
    "    \n",
    "    public static void main(String[] args) {{\n",
    "        // Warmup\n",
    "        for (int i = 0; i < 10; i++) {{\n",
    "            runBenchmark();\n",
    "        }}\n",
    "        \n",
    "        // Actual timing\n",
    "        long start = System.nanoTime();\n",
    "        runBenchmark();\n",
    "        long end = System.nanoTime();\n",
    "        \n",
    "        System.out.println((end - start) / 1_000_000);\n",
    "    }}\n",
    "    \n",
    "    private static void runBenchmark() {{\n",
    "        // Category-specific benchmark logic\n",
    "        List<Integer> items = new ArrayList<>();\n",
    "        for (int i = 0; i < {size}; i++) {{\n",
    "            items.add(i);\n",
    "        }}\n",
    "        \n",
    "        // Run the method under test\n",
    "        // This would call the buggy or fixed method\n",
    "    }}\n",
    "}}\n",
    "        \"\"\"\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    # Test the validator\n",
    "    validator = PerformanceValidator()\n",
    "    \n",
    "    # Test with synthetic benchmarks\n",
    "    generator = SyntheticBenchmarkGenerator()\n",
    "    \n",
    "    print(\"Synthetic benchmark templates:\")\n",
    "    for category in ['algorithmic_inefficiency', 'memory_usage']:\n",
    "        benchmark = generator.generate_benchmark(category)\n",
    "        print(f\"\\n{category}:\")\n",
    "        print(f\"  Buggy version: {len(benchmark.get('buggy', ''))} characters\")\n",
    "        print(f\"  Fixed version: {len(benchmark.get('fixed', ''))} characters\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}